apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ehw9mc3gw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ehw9mc3gw-go 
  name: ehw9mc3gw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ehw9mc3gw-go 
